In [2]:
#importing library
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.3.0'

In [4]:
#import data set
dataset = pd.read_csv('C:/Users/CDR Lab/Downloads/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
#label encoding gender column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
#one hot encoding the geography column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [11]:
#Spliting into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [12]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
#builing the ann model 
#initialize
ann = tf.keras.models.Sequential()

In [14]:
#input layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
#hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
#output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [17]:
#compiling ann
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [19]:
#training on training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
250/250 [==============================] - 0s 927us/step - loss: 0.6474 - accuracy: 0.6741
Epoch 2/50
250/250 [==============================] - 0s 871us/step - loss: 0.4920 - accuracy: 0.7955
Epoch 3/50
250/250 [==============================] - 0s 815us/step - loss: 0.4488 - accuracy: 0.8060
Epoch 4/50
250/250 [==============================] - 0s 808us/step - loss: 0.4287 - accuracy: 0.8100
Epoch 5/50
250/250 [==============================] - 0s 764us/step - loss: 0.4149 - accuracy: 0.8184
Epoch 6/50
250/250 [==============================] - 0s 872us/step - loss: 0.4019 - accuracy: 0.8294
Epoch 7/50
250/250 [==============================] - 0s 871us/step - loss: 0.3894 - accuracy: 0.8378
Epoch 8/50
250/250 [==============================] - 0s 883us/step - loss: 0.3778 - accuracy: 0.8455
Epoch 9/50
250/250 [==============================] - 0s 867us/step - loss: 0.3680 - accuracy: 0.8485
Epoch 10/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3621 

In [20]:
#customer to leave or not bank prediction using model
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [21]:
#test set result
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [22]:
#confusion matrix of model preiction
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1507   88]
 [ 195  210]]


0.8585